server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /index.html {
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate" always;
    expires -1;
  }

  location / {
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate" always;
    try_files $uri /index.html;
  }

  location /api/ {
    proxy_pass http://api:8080/api/;
  }

  location /docs {
    proxy_pass http://api:8080/docs;
  }

  location /health {
    proxy_pass http://api:8080/health;
  }
}
