apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testhistory
  namespace: testhistory
  annotations:
    testhistory.io/overlay: "prod-template"
    testhistory.io/parameter.host: "replace-with-production-testhistory-hostname"
    testhistory.io/parameter.tls-secret: "replace-with-production-tls-secret-name"
spec:
  ingressClassName: replace-with-production-ingress-class
  tls:
    - hosts:
        - replace-with-production-testhistory-hostname
      secretName: replace-with-production-tls-secret-name
  rules:
    - host: replace-with-production-testhistory-hostname
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: testhistory-api
                port:
                  number: 8080
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: testhistory-api
                port:
                  number: 8080
          - path: /health
            pathType: Exact
            backend:
              service:
                name: testhistory-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testhistory-web
                port:
                  number: 80
